config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets

  # root 'welcome#index'
  root 'tweets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def index
		@username = params[:search]
		@twitter_user = $twitter.user(@username ||= "StackCommerce")
		@twitter_timeline = $twitter.user_timeline(@twitter_user, {count:25})
		Rails.cache.fetch(@twitter_timeline, :expires_in => 5.minutes)
	rescue Twitter::Error::NotFound => e
		flash[:notice] = "USER NOT FOUND"
		redirect_to(:action => 'index')
	end

	def show

	end

end


# Parameters: {"utf8"=>"✓", "search"=>"elonmusk", "commit"=>"Search"}

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
  	<%= render "tweets/nav" %>
  	<% if notice %>
  	  <p class="alert alert-success"><%= notice %></p>
  	<% end %>
  	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_header.html.erb
<h1 class="brand"> Tweets </h1>

app/views/tweets/_nav.html.erb
<!-- Navigation -->
   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container">
           <!--  -->
           <div class="navbar-header col-12 col-md-6">
            <%= render :partial => "tweets/search" if user_signed_in? %>
            <%= render :partial => "tweets/header" if !user_signed_in? %>
           </div>
           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <p class="navbar-text pull-right logic">
               <% if user_signed_in? %>
                 Logged in as <strong><%= current_user.email %></strong>.
                 <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                 <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
               <% else %>
                 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                 <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
               <% end %>
               </p>
           </div>
           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container -->
   </nav>

app/views/tweets/_search.html.erb
<form class="navbar-form navbar-left searchbox" role="search">
<%= form_tag(tweets_path, :method => "get", id: "search-form") do %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Usernames" %>
        <!-- <input type="Search" class="form-control" placeholder="Search"> -->
    </div>
    <!-- <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button> -->
   <%= submit_tag "Search" %>
  <% end %>
</form>

app/views/tweets/index.html.erb
   <!-- Page Content -->
   <div class="container">

       <!-- Jumbotron Header -->
       <header class="jumbotron hero-spacer">
           <h1 class="text-center"><%= @twitter_user.user_name %></h1>
<!--            <p>Enjoy.</p> -->
       </header>

       <hr>

       <!-- Title -->
       <div class="row">
           <div class="col-lg-12">
               <h3>Recent Tweets</h3>
           </div>
       </div>
       <!-- /.row -->

       <!-- Page Features -->
       <div class="row text-center">
       	<% @twitter_timeline.each do |tweet| %>
       	  <tr>
           <div class="col-md-12 hero-feature">
               <div class="thumbnail">
                   <!-- <img src="http://placehold.it/800x500" alt=""> -->
                   <div class="caption">
                       <h3></h3>
                       <p><%= tweet.full_text %></p>
                       <p><%= tweet.created_at %></p>
                   </div>
               </div>
           </div>
       	  </tr>
       	<% end %>


       </div>
       <!-- /.row -->

       <hr>

       <!-- Footer -->
       <footer>
           <div class="row">
               <div class="col-lg-12">
                   <p></p>
               </div>
           </div>
       </footer>

   </div>
   <!-- /.container -->

   <!-- jQuery -->
   <script src="js/jquery.js"></script>

   <!-- Bootstrap Core JavaScript -->
   <script src="js/bootstrap.min.js"></script>

app/views/tweets/show.html.erb
<h1>Listing Tweets</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @twitter_timeline.each do |tweet| %>
    <tr>
      <td><%= tweet.title %></td>
      <td><%= tweet.text %></td>
      <td><%= link_to 'Show', tweets_path(tweet) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>